import React, { useState } from 'react';
import { ArrowRight, ArrowUpRight, BookOpen, Headphones, Mic2, PenLine, Quote, Sparkles } from 'lucide-react';
import { Language } from '../types';

interface PortedProgressSectionsProps { lang: Language; onOpenTestModal: () => void; }

const stories = {
  ru: [
    { name: 'Алина К.', meta: 'IELTS Academic · Алматы', score: '5.5 → 6.5', label: 'Writing', quote: 'За 6 недель я подняла Writing с 5.5 до 6.5. Наконец-то понимаю, что именно улучшать и как.', avatar: '/success-stories/candidate-01.png' },
    { name: 'Марат С.', meta: 'TOEFL · Астана', score: '78 → 94', label: 'Speaking', quote: 'Раньше я просто много говорил. Теперь вижу паузы, слабые связки и знаю, как исправить ответ за одну попытку.', avatar: '/success-stories/candidate-02.png' },
    { name: 'Диана Т.', meta: 'IELTS Academic · Шымкент', score: '6.0 → 7.5', label: 'Overall', quote: 'Самое полезное — платформа не даёт утонуть в теории. Каждый день я вижу один понятный следующий шаг.', avatar: '/success-stories/candidate-03.png' },
  ],
  en: [
    { name: 'Alina K.', meta: 'IELTS Academic · Almaty', score: '5.5 → 6.5', label: 'Writing', quote: 'In six weeks, I moved Writing from 5.5 to 6.5. I finally understand what to improve and how.', avatar: '/success-stories/candidate-01.png' },
    { name: 'Marat S.', meta: 'TOEFL · Astana', score: '78 → 94', label: 'Speaking', quote: 'I used to just talk more. Now I see my pauses, weak links and know how to fix an answer in one try.', avatar: '/success-stories/candidate-02.png' },
    { name: 'Diana T.', meta: 'IELTS Academic · Shymkent', score: '6.0 → 7.5', label: 'Overall', quote: 'The best part is not drowning in theory. Every day I get one clear next step and a short way to practise it.', avatar: '/success-stories/candidate-03.png' },
  ],
  kz: [
    { name: 'Алина К.', meta: 'IELTS Academic · Алматы', score: '5.5 → 6.5', label: 'Writing', quote: 'Алты аптада Writing нәтижемді 5.5-тен 6.5-ке көтердім. Енді нені және қалай жақсартуды түсінемін.', avatar: '/success-stories/candidate-01.png' },
    { name: 'Марат С.', meta: 'TOEFL · Астана', score: '78 → 94', label: 'Speaking', quote: 'Бұрын тек көп сөйлейтінмін. Енді үзілістерімді көріп, жауапты бір әрекетте жақсартуды білемін.', avatar: '/success-stories/candidate-02.png' },
    { name: 'Диана Т.', meta: 'IELTS Academic · Шымкент', score: '6.0 → 7.5', label: 'Overall', quote: 'Ең пайдалысы — теорияға батып кетпеймін. Күн сайын келесі бір нақты қадамды көремін.', avatar: '/success-stories/candidate-03.png' },
  ],
} as const;

const skills = [
  { id: 'listening', label: 'Listening', score: '7.0', icon: Headphones, color: 'orange', width: 70 },
  { id: 'reading', label: 'Reading', score: '7.0', icon: BookOpen, color: 'orange', width: 72 },
  { id: 'writing', label: 'Writing', score: '6.0', icon: PenLine, color: 'rose', width: 58 },
  { id: 'speaking', label: 'Speaking', score: '6.5', icon: Mic2, color: 'amber', width: 66 },
] as const;

const copy = {
  ru: { storiesEyebrow: 'Истории учеников', storiesTitle: 'Результат слышно ещё до экзамена.', storiesBody: 'Не обещания из рекламы, а реальные изменения в ответах, баллах и уверенности.', storiesLabel: 'Отзыв ученика', browse: 'Листать отзывы', averageGrowth: 'Средний рост', progressEyebrow: 'Твой прогресс', progressTitle: 'Четыре навыка. Один понятный маршрут.', progressBody: 'Платформа показывает, где теряются баллы, и подсказывает, что улучшить сегодня.', mockTest: 'ПРОБНЫЙ ТЕСТ · АКАДЕМИЧЕСКИЙ IELTS', current: 'Где ты сейчас', updated: 'обновлено сейчас', weakSpot: 'Слабое место', steady: 'стабильный прогресс', currentBand: 'текущий балл', scoreLabel: 'ТВОЙ БАЛЛ', inSixWeeks: '+1.2 ЗА 6 НЕДЕЛЬ', next: 'Следующий шаг', writingNext: 'Coherence & Cohesion', writingBody: 'Собери ответ по схеме: тезис → причина → пример. Это самый быстрый путь к 6.5+.', practiceBody: 'Персональная подборка заданий уже готова. Один короткий блок даст понятный следующий шаг.', start: 'Начать практику' },
  en: { storiesEyebrow: 'Student stories', storiesTitle: 'You can hear the progress before test day.', storiesBody: 'Not ad promises: real changes in answers, scores and confidence.', storiesLabel: 'Student story', browse: 'Browse stories', averageGrowth: 'Average growth', progressEyebrow: 'Your progress', progressTitle: 'Four skills. One clear route.', progressBody: 'See where points disappear and what to improve today.', mockTest: 'MOCK TEST · ACADEMIC IELTS', current: 'Where you are now', updated: 'updated now', weakSpot: 'Needs focus', steady: 'steady progress', currentBand: 'current band', scoreLabel: 'YOUR SCORE', inSixWeeks: '+1.2 IN 6 WEEKS', next: 'Next step', writingNext: 'Coherence & Cohesion', writingBody: 'Build your answer as point → reason → example. It is the fastest route to 6.5+.', practiceBody: 'Your personal practice set is ready. One short block gives you a clear next step.', start: 'Start practice' },
  kz: { storiesEyebrow: 'Оқушылар тарихы', storiesTitle: 'Нәтиже емтиханға дейін естіледі.', storiesBody: 'Жарнама уәдесі емес: жауаптардағы, баллдағы және сенімділіктегі нақты өзгеріс.', storiesLabel: 'Оқушы пікірі', browse: 'Пікірлерді көру', averageGrowth: 'Орташа өсім', progressEyebrow: 'Прогресің', progressTitle: 'Төрт дағды. Бір түсінікті бағыт.', progressBody: 'Ұпайдың қайда жоғалатынын және бүгін нені жақсарту керегін көр.', mockTest: 'СЫНАҚ ТЕСТ · IELTS ACADEMIC', current: 'Қазіргі деңгейің', updated: 'қазір жаңартылды', weakSpot: 'Назар аудару керек', steady: 'тұрақты прогресс', currentBand: 'ағымдағы балл', scoreLabel: 'СЕНІҢ БАЛЛЫҢ', inSixWeeks: '+1.2 6 АПТАДА', next: 'Келесі қадам', writingNext: 'Coherence & Cohesion', writingBody: 'Жауапты тезис → себеп → мысал схемасымен құр. Бұл 6.5+ деңгейіне жетудің ең жылдам жолы.', practiceBody: 'Жеке тапсырмалар жинағы дайын. Бір қысқа блок келесі қадамды түсіндіреді.', start: 'Жаттығуды бастау' },
} as const;

export const PortedProgressSections: React.FC<PortedProgressSectionsProps> = ({ lang, onOpenTestModal }) => {
  const t = copy[lang];
  const [activeStory, setActiveStory] = useState(0);
  const [activeSkill, setActiveSkill] = useState('writing');
  const story = stories[lang][activeStory];
  const activeSkillData = skills.find(skill => skill.id === activeSkill) ?? skills[2];
  return <>
    <section id="student-stories" className="ported-stories py-20 md:py-28"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="ported-section-heading reveal"><div><span className="ported-kicker">{t.storiesEyebrow}</span><h2>{t.storiesTitle}</h2></div><p>{t.storiesBody}</p></div><div className="ported-story-stage reveal reveal-right"><div className="ported-story-main"><div className="ported-story-copy"><span className="ported-kicker">{t.storiesLabel}</span><Quote size={30} /><p>{story.quote}</p><div className="ported-story-person"><strong>{story.name}</strong><small>{story.meta}</small></div></div><div className="ported-story-visual"><img src={story.avatar} alt={story.name} /><div className="ported-story-score"><span>{story.label}</span><strong>{story.score}</strong><i /></div></div></div><aside className="ported-story-rail"><div className="ported-story-rail-top"><span>REAL PROGRESS / 0{activeStory + 1}</span><span>{t.browse}</span></div><div className="ported-story-list">{stories[lang].map((item, index) => <button type="button" key={item.name} className={activeStory === index ? 'is-active' : ''} onClick={() => setActiveStory(index)}><span className="ported-story-avatar"><img src={item.avatar} alt="" /></span><span><strong>{item.name}</strong><small>{item.meta}</small></span><ArrowUpRight size={16} /></button>)}</div><div className="ported-story-foot"><span>{t.averageGrowth}</span><strong>+1.2 band</strong></div></aside></div></div></section>
    <section id="student-progress" className="ported-progress py-20 md:py-28"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="ported-section-heading reveal"><div><span className="ported-kicker">{t.progressEyebrow}</span><h2>{t.progressTitle}</h2></div><p>{t.progressBody}</p></div><div className="ported-progress-board reveal reveal-right"><div className="ported-progress-visual"><div className="ported-progress-ring"><div><strong>6.8</strong><span>{t.currentBand}</span></div></div><span className="ported-progress-label">{t.scoreLabel}<br /><strong>{t.inSixWeeks}</strong></span><img src="/hero-study.png" alt="" aria-hidden="true" /><div className="ported-progress-float"><span><Sparkles size={15} /></span><div><small>{t.next}</small><strong>Writing · 12 min</strong></div><ArrowUpRight size={15} /></div></div><div className="ported-progress-matrix"><div className="ported-progress-top"><div><span className="ported-mono">{t.mockTest}</span><h3>{t.current}</h3></div><span className="ported-live"><i /> {t.updated}</span></div>{skills.map(({ id, label, score, icon: Icon, color, width }) => <button type="button" key={id} className={`ported-skill-row ported-skill-row--${color} ${activeSkill === id ? 'is-active' : ''}`} onClick={() => setActiveSkill(id)}><span className="ported-skill-icon"><Icon size={17} /></span><span className="ported-skill-name"><strong>{label}</strong><small>{id === 'writing' ? t.weakSpot : t.steady}</small></span><strong className="ported-skill-score">{score}</strong><span className="ported-skill-bar"><i style={{ width: `${width}%` }} /></span><span className="ported-skill-trend">+{id === 'writing' ? '0.8' : '0.4'} <ArrowUpRight size={14} /></span></button>)}<div className="ported-progress-detail"><div><span className="ported-detail-label">{t.next}</span><h3>{activeSkill === 'writing' ? t.writingNext : `${activeSkillData.label} practice`}</h3><p>{activeSkill === 'writing' ? t.writingBody : t.practiceBody}</p></div><button className="button brand-gradient text-white" type="button" onClick={onOpenTestModal}>{t.start}<ArrowRight size={16} /></button></div></div></div></div></section>
  </>;
};

